name: cashflow
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  path: ^1.9.0
  share_plus: ^10.1.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.4
  jwt_decoder: ^2.0.1
  tutorial_coach_mark: ^1.2.12
  fl_chart: ^0.70.2
  flutter_local_notifications: ^18.0.1
  provider: ^6.1.2
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
